CREATE TABLE bd_countryzone (code varchar(40), modifier varchar(50), pk_timezone varchar(20), creator varchar(50), phonecode varchar(20), wholename varchar(200), name varchar(200), description varchar(100), pk_lang varchar(50), creationtime datetime, modifiedtime datetime, pk_country char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (pk_country)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE cardtablemeta (radiodataassociate varchar(50), radiodatacontroller varchar(50), CODE varchar(50), NAME varchar(100), combodatamodel varchar(50), gateway varchar(50), tag varchar(50), createtime datetime, pk_system char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (pk_system)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE cardtable (name varchar(100) NOT NULL, code varchar(50) NOT NULL, pk_system varchar(50) NOT NULL, i18n varchar(50), gateway varchar(100), radiodatacontroller varchar(50), radiodataassociate varchar(50), combodatamodel varchar(50), tag varchar(50), system varchar(50), tenant varchar(50), ts timestamp NULL, dr decimal, secretkey varchar(50), createtime timestamp DEFAULT CURRENT_TIMESTAMP NULL, PRIMARY KEY (pk_system)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dept (parent_id varchar(36), short_name varchar(50), dept_type varchar(20), org_id varchar(50) NOT NULL, creator varchar(20), dept_name varchar(50), dept_code varchar(40) NOT NULL, deptcanceldate datetime, creationtime datetime, createdate datetime, pk_dept char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (pk_dept)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_bd_countryzone (ext_pk_country char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_pk_country)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_cardtablemeta (ext_pk_system char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_pk_system)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_dept (ext_pk_dept char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_pk_dept)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_instit (ext_institid char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_institid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_org (ext_org_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_org_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_sys_dict_type_meta (ext_dict_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_dict_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_sys_user (ext_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_sys_user_job (ext_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ext_telbook (ext_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (ext_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE instit (parent_id varchar(36), instit_code varchar(200) NOT NULL, email varchar(50), short_name varchar(50), instit_type varchar(10), instit_name varchar(200) NOT NULL, creator varchar(20), creationtime datetime, institid char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (institid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_accessorpara (id varchar(128) NOT NULL, assosequence smallint NOT NULL, paravalue varchar(512), versiontype smallint, industry varchar(50), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, assosequence)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_association (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(60) NOT NULL, componentid varchar(50), startbeanid varchar(50) NOT NULL, startelementid varchar(50) NOT NULL, endelementid varchar(50) NOT NULL, startcardinality varchar(10), endcardinality varchar(10), type smallint, cascadeupdate char(1), cascadedelete char(1), isactive char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), industry varchar(50), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_bizitfmap (bizinterfaceid varchar(50) NOT NULL, intattrid varchar(50) NOT NULL, classid varchar(50) NOT NULL, classattrid varchar(50), bizitfimpclassname varchar(256), classattrpath varchar(512), versiontype smallint, industry varchar(50), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (intattrid, classid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE md_class (id varchar(50) NOT NULL, versiontype smallint NOT NULL, parentclassid varchar(50), componentid varchar(50), keyattribute varchar(50), name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), fullclassname varchar(256), classtype smallint, accessorclassname varchar(256), fixedlength char(1), precise smallint, refmodelname varchar(768), returntype varchar(50), isprimary char(1), isactive char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), isauthen char(1), resid varchar(90), bizitfimpclassname varchar(256), modinfoclassname varchar(256), iscreatesql char(1), defaulttablename varchar(50), isextendbean char(1), userdefclassname varchar(256), stereotype varchar(256), industry varchar(50) NOT NULL, tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype, industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE md_column (id varchar(50) NOT NULL, versiontype smallint NOT NULL, tableid varchar(50), name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), isactive char(1), sqldatetype varchar(50), pkey char(1), identitied char(1), incrementstep smallint, incrementseed smallint, nullable char(1), precise smallint, columnlength smallint, defaultvalue varchar(512), columnsequence smallint, modifytime char(19), createtime char(19), modifier varchar(30), creator varchar(30), resid varchar(90), groupid varchar(50), columntype smallint, forlocale char(1), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE md_comp_busimodule (componentid varchar(50) NOT NULL, busimodulecode varchar(50), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (componentid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_component (id varchar(50) NOT NULL, versiontype smallint NOT NULL, namespace varchar(512), ownmodule varchar(50), name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), version varchar(512), resmodule varchar(90), resid varchar(90), preload char(1), isbizmodel char(1), fromsourcebmf char(1), industry varchar(50) NOT NULL, tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype, industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_db (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), isactive char(1) NOT NULL, modifytime char(19), createtime char(19), modifier varchar(30), creator varchar(30), resid varchar(90), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_db_relation (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(90) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), starttableid varchar(50) NOT NULL, startfieldid varchar(50) NOT NULL, startattrid varchar(50), startcardinality varchar(10), endtableid varchar(50) NOT NULL, endfieldid varchar(50) NOT NULL, endcardinality varchar(10), asstype smallint, creator varchar(30), createtime char(19), modifier varchar(30), modifytime char(19), resid varchar(90), isforeignkey char(1), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_enumvalue (id varchar(50) NOT NULL, versiontype smallint NOT NULL, value varchar(128) NOT NULL, name varchar(512), description varchar(512), resid varchar(90), enumsequence smallint, hidden char(1), industry varchar(50) NOT NULL, tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype, value, industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_module (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), parentmoduleid varchar(50), isactive char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), resid varchar(90), resmodule varchar(90), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE md_opinterface (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), parentid varchar(50), componentid varchar(50) NOT NULL, fullclassname varchar(256), isservice char(1), visibility smallint, remote char(1), singleton char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), implstrategy varchar(256), resid varchar(90), authorizable char(1), ownertype varchar(50), defaultimplclassname varchar(256), isbusioperation char(1), isbusiactivity char(1), industry varchar(50) NOT NULL, tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype, industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_ormap (classid varchar(50) NOT NULL, attributeid varchar(50) NOT NULL, tableid varchar(50) NOT NULL, columnid varchar(50) NOT NULL, tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (attributeid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE md_parameter (id varchar(50) NOT NULL, versiontype smallint NOT NULL, operationid varchar(50), name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), datatype varchar(50) NOT NULL, datatypestyle smallint NOT NULL, parasequence smallint NOT NULL, modifier varchar(30), creator varchar(30), createtime char(19), modifytime char(19), resid varchar(90), paramdefclassname varchar(50), isaggvo char(1), paramtypeforlog varchar(10), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_property (id varchar(50) NOT NULL, versiontype smallint NOT NULL, name varchar(50) NOT NULL, displayname varchar(90), description varchar(512), help varchar(1024), classid varchar(50), defaultvalue varchar(512), attrminvalue varchar(50), attrmaxvalue varchar(50), fixedlength char(1), attrlength smallint, precise smallint, datatype varchar(50), datatypestyle smallint, nullable char(1), customattr char(1), calculation char(1), readonly char(1), visibility smallint, accessorclassname varchar(256), attrsequence smallint, hided char(1), refmodelname varchar(256), isactive char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), isauthen char(1), resid varchar(90), dynamicattr char(1), notserialize char(1), accesspower char(1), accesspowergroup varchar(256), industry varchar(50) NOT NULL, createindustry varchar(50), tenantid varchar(50), dynamictable varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id, versiontype, industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_sysmoduleconfig (tablename varchar(50), codefield varchar(50), namefield varchar(50), resmodulefield varchar(50), resmodulevalue varchar(50), residfield varchar(50), tenantid varchar(50), ts char(19), dr decimal DEFAULT '0') ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE md_table (id varchar(50) NOT NULL, versiontype smallint NOT NULL, displayname varchar(90), name varchar(50) NOT NULL, databaseid varchar(50), description varchar(512), help varchar(1024), isactive char(1), creator varchar(30), modifier varchar(30), createtime char(19), modifytime char(19), resid varchar(90), parenttable varchar(50), isextendtable char(1), fromsourcebmf char(1), industry varchar(50), tenantid varchar(50), resmodule varchar(50), ts char(19), dr decimal DEFAULT '0', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE org (parent_id varchar(36), org_name varchar(200) NOT NULL, email varchar(50), short_name varchar(50), creator varchar(20), org_type varchar(10), org_code varchar(200) NOT NULL, creationtime datetime, org_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (org_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE pub_multilang (CHARSETNAME varchar(50), DISLPAYNAME char(75), dr decimal DEFAULT '0', LANGCODE varchar(50), LANGDIRPATH varchar(50), LANGSEQ decimal, LOCALCOUNTRY varchar(50), LOCALLANG varchar(50), PK_MULTILANG varchar(50) NOT NULL, TRANSCLASSNAME varchar(50), ts char(19), PRIMARY KEY (PK_MULTILANG)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sys_dict_type (dict_id varchar(40) NOT NULL, dict_type_code varchar(100) NOT NULL, dict_type_name varchar(100) NOT NULL, is_fixed char(1) DEFAULT 'N' NOT NULL, remark varchar(512), creator_id varchar(40) NOT NULL, creator varchar(20) NOT NULL, create_time date NOT NULL, modifier_id varchar(40), modifier varchar(20), modify_time date, Dr char(1) DEFAULT '0' NOT NULL, PRIMARY KEY (dict_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sys_dict_type_meta (dict_type_code varchar(100), creator_id varchar(40), is_fixed varchar(50), modifier varchar(20), remark varchar(512), creator varchar(20), modifier_id varchar(40), dict_type_name varchar(100), create_time datetime, modify_time datetime, dict_id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (dict_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sys_prompt (moudle varchar(32) NOT NULL, error_code varchar(32) NOT NULL, error_version varchar(32) NOT NULL, error_desc varchar(32), error_cause varchar(255), error_solution varchar(255), locale varchar(32), PRIMARY KEY (moudle, error_code, error_version)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sys_user (org_id char(36) NOT NULL, sex_id varchar(50), modifier varchar(20), remark varchar(512), platform_id varchar(1), login_name varchar(64), creator varchar(20), platform_name varchar(16), modifier_id varchar(40), status_id varchar(1), certificate_name varchar(16), user_mobile varchar(16), level_name varchar(16), user_code varchar(32), user_password varchar(64), certificate_code varchar(32), image_url varchar(64), certificate_id varchar(1), level_id varchar(1), org_name varchar(64), status_name varchar(16), user_email varchar(64), user_name varchar(20), creator_id varchar(40), birthdate datetime, register_date datetime, modify_time datetime, create_time datetime, id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sys_user_job (dept_id char(36) NOT NULL, org_id char(36) NOT NULL, user_job_note varchar(256), user_id varchar(40) NOT NULL, creator varchar(20) NOT NULL, creator_id varchar(40) NOT NULL, is_default varchar(50) NOT NULL, is_active varchar(50), modifier varchar(20), modifier_id varchar(40), user_name varchar(24) NOT NULL, create_time datetime NOT NULL, modify_time datetime, id char(36) NOT NULL, fk_id_sys_user_job char(36), ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (id), INDEX fk__job__job557408 (fk_id_sys_user_job)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE telbook (countryzone varchar(36), institid char(36), sex varchar(50), tel varchar(100), email varchar(100), worktel varchar(100), office varchar(100), peoname varchar(50) NOT NULL, peocode varchar(100) NOT NULL, id char(36) NOT NULL, ts datetime, dr smallint DEFAULT '0', PRIMARY KEY (id), INDEX fk_book_itid39472 (institid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
